project_id = "gifovgwlxwuiibfzyvwb"

[functions.bunny-stream]
verify_jwt = false

[functions.bunny-embed]
verify_jwt = false

[functions.video-proxy]
verify_jwt = false

[functions.tap-create-charge]
verify_jwt = false

[functions.tap-webhook]
verify_jwt = false

[functions.tap-config]
verify_jwt = false

[functions.tap-verify-charge]
verify_jwt = false

[functions.coupon-validate]
verify_jwt = false

[functions.transcode-video]
verify_jwt = false

[functions.ghl-sync]
verify_jwt = false

[functions.ghl-form-webhook]
verify_jwt = false

[functions.signup-user]
verify_jwt = false

[functions.self-update-password]
verify_jwt = false

[functions.meta-product-feed]
verify_jwt = false